### ISSUE TITLE
easy_localization_loader ^0.0.2 is incompatible with flutter_svg >=0.18.0

### ISSUE THREAD

**Issue by Ya-seeen** [aissat/easy_localization_loader#13]
Because no versions of easy_localization_loader match >0.0.2 <0.1.0 and easy_localization_loader 0.0.2 depends on xml ^3.5.0, easy_localization_loader ^0.0.2 requires xml ^3.5.0.
Because flutter_svg >=0.18.1 depends on xml ^4.2.0 and flutter_svg >=0.18.0 <0.18.1 depends on xml ^4.1.0, flutter_svg >=0.18.0 requires xml ^4.1.0.
Thus, easy_localization_loader ^0.0.2 is incompatible with flutter_svg >=0.18.0.
So, because cip depends on both flutter_svg ^0.18.0 and easy_localization_loader ^0.0.2, version solving failed.
Running "flutter pub get" in cip...                                     
pub get failed (1; So, because cip depends on both flutter_svg ^0.18.0 and easy_localization_loader ^0.0.2, version solving failed.)

**Comment by Ya-seeen** [comment]
please upgrade your XML version. It may solve the problem.

**Comment by deadsoul44** [comment]
Upgrading xml didn't help. Could you please upgrade the dependency?

**Comment by Ya-seeen** [comment]
for me, that didn't work. So I removed the dependency for XML from the plugin as I didn't need the XML portion and then everything worked fine.

**Comment by amzac-rait** [comment]
Changing pubspec to last develop commit works too (you can select `ref: develop` too i guess):
```
  easy_localization_loader:
    git:
      url: git@github.com:aissat/easy_localization_loader.git
      ref: 77ccb7b5918b64996cfc573f235d178e5a38f18b

```
